apiVersion: v1
kind: Service
metadata:
  name: my-chatgpt-frontend
  labels:
    app: my-chatgpt-frontend
spec:
  type: LoadBalancer
  selector:
    app: my-chatgpt-frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  sessionAffinity: None
